### ISSUE TITLE
Cameras not loading in Octoprint native sidebar widget, some cams load OK on Edge, all cams load on FF. Go Figure!

### ISSUE THREAD

**Issue by marioPS** [mikedmor/OctoPrint_MultiCam#63]
Pretty much all in the subject field!
BTW: Classic webcam is disabled:
![Screenshot 2023-08-06 at 7 13 29 pm](https://github.com/mikedmor/OctoPrint_MultiCam/assets/11381244/26b8afe8-4a17-4fdf-ba19-e09869d9d972)

Config:
![Screenshot 2023-08-06 at 6 56 17 pm](https://github.com/mikedmor/OctoPrint_MultiCam/assets/11381244/6184f121-31d0-4e12-94e4-fa25386ea26d)

Both cams working in FF in 'Control' View:
![Screenshot 2023-08-06 at 7 00 22 pm](https://github.com/mikedmor/OctoPrint_MultiCam/assets/11381244/d0e81e34-7b65-4e42-8033-ea8ee3bac643)
![Screenshot 2023-08-06 at 7 00 09 pm](https://github.com/mikedmor/OctoPrint_MultiCam/assets/11381244/b7cbcbc5-829a-4125-bae2-c3743a72ab32)

But not in the sidebar:
![Screenshot 2023-08-06 at 7 00 58 pm](https://github.com/mikedmor/OctoPrint_MultiCam/assets/11381244/a3c34958-1701-4300-91ba-9a05ebd124b9)

And Edge doesn't like the webstreaming cam:
![0](https://github.com/mikedmor/OctoPrint_MultiCam/assets/11381244/c741da8b-c253-4548-ac53-6cb77e1ab577)
But FF is OK with it (Windows & Mac):
![Screenshot 2023-08-06 at 7 01 31 pm](https://github.com/mikedmor/OctoPrint_MultiCam/assets/11381244/9a5b6c35-4e4b-4c48-8c83-323d58fb2681)

Config:
NozzleCam
http://[externalIP]:8081/camera/mjpeg
http://[externalIP]8081/camera/jpeg

JobbieCam
http://admin:camera@[internalIP]:80/video.cgi
http://admin:camera@internalIP]:80/image/jpeg.cgi

Let me know if you need any more info - & thanks in advance for your help!

Mikey!

**Comment by LazeMSS** [comment]
This is a UI Customizer plugin error - im fixing it now.

**Comment by marioPS** [comment]
Magnificent @LazeMSS - thank you for your fast response!

Edge now no longer "Loading webcam", but still does not stream JobbieCam.
[http://admin:camera@[internalIP]:80/video.cgi](http://admin:camera@%5BinternalIP%5D:80/video.cgi)
FF on both platforms working OK.

I hope this helps!

Mikey.

**Comment by LazeMSS** [comment]
Should be fixed in laterst release of UI Customizer - please close if you agree @marioPS

**Comment by marioPS** [comment]
Hi @LazeMSS Edge still having problem as previously explained.
Also, unable to get JobbieCam  http://admin:camera@[internalIP]:80/image/jpeg.cgi to provide still images for Timelapse …
Unknown if related.

**Comment by LazeMSS** [comment]
What is Jobbiecam ?

**Comment by marioPS** [comment]
Sorry! That's one of the two cams aimed at my printer: JobbieCam at bed (wifi camera), NozzleCam at the Nozzle (endoscope USB).
BTW: Just tested Chrome - same as Edge.
In both cases, I cannot switch cameras in the sidebar, but can in the main central view.

**Comment by LazeMSS** [comment]
Strange I have no problems
